### ***Python Pandas***  

Pandas is an open-source Python library used for data manipulation, cleaning, and analysis

In [1]:
import pandas as pd

***Series***   

A 1-dimensional labeled array capable of holding any data type

In [2]:
car_name = pd.Series(["BMW", "Mercedes", "Opel", "Mazda", "Toyota", "Honda", "Ford", "Fiat", "Renault", "Peugeot"])
car_name

0         BMW
1    Mercedes
2        Opel
3       Mazda
4      Toyota
5       Honda
6        Ford
7        Fiat
8     Renault
9     Peugeot
dtype: str

***DataFrame***  

A 2-dimensional labeled data structure with columns and rows and more then 2 series can form as DataFrame

In [3]:
car_color = pd.Series(["Red", "Blue", "Green", "Black", "White", "Silver", "Yellow", "Orange", "Purple", "Brown"])
car_data = pd.DataFrame({"Car Name": car_name, "Car Color": car_color})
car_data

   Car Name Car Color
0       BMW       Red
1  Mercedes      Blue
2      Opel     Green
3     Mazda     Black
4    Toyota     White
5     Honda    Silver
6      Ford    Yellow
7      Fiat    Orange
8   Renault    Purple
9   Peugeot     Brown

In [15]:
# To read a csv file, you can use the following code:
df = pd.read_csv("R:\Gen AI\Pandas Sample.csv")
df

,First Name,Last Name,Address (Street),City,State,Zip Code
0,NICK,SAMPLE,123 STATE ST,OKLAHOMA CITY,OK,73102-1234
1,BRENDA LYNN,SAMPLE,123 MAIN Street,HELENA,MT,59601
2,TIM,COOK,1 Infinite Loop,Cupertino,CA,95014
3,MARK,PERLSON,123 MAIN ST,ANYTOWN,USA,NaN
4,RENEE A,ANDRE,3300 ACORN STREET,AUSTIN,TX,12345-0000
5,MARIE NAKITA,ANDERSON,8254 PIMPU LN 645,SAN MARCOS,TX,78666
6,JANICE,SAMPLE,2230 HESSLER BOULEVARD,NEW CASTLE,DE,19720-0000
7,"SAMUEL DANIEL, JR",SAMPLECARD,123 RAILROAD AVE SE,WASHINGTON,DC,20001-0000
8,TINA A,SAMPLE,123 ANYSTREET,ANYTOWN,WY,82000
9,DEREK THOMAS,SAMPLE,4802 SHEBOYGAN AVE,MADISON,WI,53705
10,"GLENDA, REILLY",BANISTER,4050 VALLEY PIKE,WINCHESTER,VA,22602
11,IMANI,WILSON,1234 YOUR STREET,ATLANTS,GA,30309
12,BRITTNEY RENA,SORRELL,5743 BELCREST ST,HOUSTON,TX,77033
13,ANDREW JASON,SAMPLE,123 MAIN STREET APT. 1,HARRISBURG,PA,17101-0000
14,"MICHELLE, MARIE",MOTORIST,2345 ANYWHERE STREET,ALBANY,NY,12222

In [22]:
#Exporting the DataFrame to a CSV file without the index column:
df.to_csv("Sample.csv", index=False)

In [23]:
new_df = pd.read_csv("Sample.csv")
new_df

,First Name,Last Name,Address (Street),City,State,Zip Code
0,NICK,SAMPLE,123 STATE ST,OKLAHOMA CITY,OK,73102-1234
1,BRENDA LYNN,SAMPLE,123 MAIN Street,HELENA,MT,59601
2,TIM,COOK,1 Infinite Loop,Cupertino,CA,95014
3,MARK,PERLSON,123 MAIN ST,ANYTOWN,USA,NaN
4,RENEE A,ANDRE,3300 ACORN STREET,AUSTIN,TX,12345-0000
5,MARIE NAKITA,ANDERSON,8254 PIMPU LN 645,SAN MARCOS,TX,78666
6,JANICE,SAMPLE,2230 HESSLER BOULEVARD,NEW CASTLE,DE,19720-0000
7,"SAMUEL DANIEL, JR",SAMPLECARD,123 RAILROAD AVE SE,WASHINGTON,DC,20001-0000
8,TINA A,SAMPLE,123 ANYSTREET,ANYTOWN,WY,82000
9,DEREK THOMAS,SAMPLE,4802 SHEBOYGAN AVE,MADISON,WI,53705
10,"GLENDA, REILLY",BANISTER,4050 VALLEY PIKE,WINCHESTER,VA,22602
11,IMANI,WILSON,1234 YOUR STREET,ATLANTS,GA,30309
12,BRITTNEY RENA,SORRELL,5743 BELCREST ST,HOUSTON,TX,77033
13,ANDREW JASON,SAMPLE,123 MAIN STREET APT. 1,HARRISBURG,PA,17101-0000
14,"MICHELLE, MARIE",MOTORIST,2345 ANYWHERE STREET,ALBANY,NY,12222

In [24]:
#attributes of the DataFrame
new_df.dtypes

First Name          str
Last Name           str
Address (Street)    str
City                str
State               str
Zip Code            str
dtype: object

In [25]:
#Functions to get describe the data
new_df.describe()

       First Name Last Name Address (Street)     City State    Zip Code
count          15        15               15       15    15          14
unique         15        10               15       14    13          14
top          NICK    SAMPLE     123 STATE ST  ANYTOWN    TX  73102-1234
freq            1         6                1        2     3           1

In [26]:
#Function to get the index of the DataFrame
new_df.index

RangeIndex(start=0, stop=15, step=1)

In [27]:
#Function to get the information about the DataFrame
new_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   First Name        15 non-null     str
 1   Last Name         15 non-null     str
 2   Address (Street)  15 non-null     str
 3   City              15 non-null     str
 4   State             15 non-null     str
 5   Zip Code          14 non-null     str
dtypes: str(6)
memory usage: 1.6 KB

In [34]:
#Fuction to get the single column of the DataFrame
new_df["Zip Code"]

0     73102-1234
1          59601
2          95014
3            NaN
4     12345-0000
5          78666
6     19720-0000
7     20001-0000
8          82000
9          53705
10         22602
11         30309
12         77033
13    17101-0000
14         12222
Name: Zip Code, dtype: str

In [35]:
#Function to get the size of the DataFrame
new_df.size

90

In [36]:
#Functions to get the shape of the DataFrame
new_df.shape

(15, 6)

***Viewing and Selecting Data***  
Heads & Tails

In [37]:
#head return the first 5 rows of the DataFrame
new_df.head()

    First Name Last Name   Address (Street)           City State    Zip Code
0         NICK    SAMPLE       123 STATE ST  OKLAHOMA CITY    OK  73102-1234
1  BRENDA LYNN    SAMPLE    123 MAIN Street         HELENA    MT       59601
2          TIM      COOK    1 Infinite Loop      Cupertino    CA       95014
3         MARK   PERLSON        123 MAIN ST        ANYTOWN   USA         NaN
4      RENEE A     ANDRE  3300 ACORN STREET         AUSTIN    TX  12345-0000

In [38]:
new_df.head(7)

,First Name,Last Name,Address (Street),City,State,Zip Code
0,NICK,SAMPLE,123 STATE ST,OKLAHOMA CITY,OK,73102-1234
1,BRENDA LYNN,SAMPLE,123 MAIN Street,HELENA,MT,59601
2,TIM,COOK,1 Infinite Loop,Cupertino,CA,95014
3,MARK,PERLSON,123 MAIN ST,ANYTOWN,USA,NaN
4,RENEE A,ANDRE,3300 ACORN STREET,AUSTIN,TX,12345-0000
5,MARIE NAKITA,ANDERSON,8254 PIMPU LN 645,SAN MARCOS,TX,78666
6,JANICE,SAMPLE,2230 HESSLER BOULEVARD,NEW CASTLE,DE,19720-0000

In [39]:
#tail return the last 5 rows of the DataFrame
new_df.tail()

,First Name,Last Name,Address (Street),City,State,Zip Code
10,"GLENDA, REILLY",BANISTER,4050 VALLEY PIKE,WINCHESTER,VA,22602
11,IMANI,WILSON,1234 YOUR STREET,ATLANTS,GA,30309
12,BRITTNEY RENA,SORRELL,5743 BELCREST ST,HOUSTON,TX,77033
13,ANDREW JASON,SAMPLE,123 MAIN STREET APT. 1,HARRISBURG,PA,17101-0000
14,"MICHELLE, MARIE",MOTORIST,2345 ANYWHERE STREET,ALBANY,NY,12222

In [40]:
new_df.tail(7)

,First Name,Last Name,Address (Street),City,State,Zip Code
8,TINA A,SAMPLE,123 ANYSTREET,ANYTOWN,WY,82000
9,DEREK THOMAS,SAMPLE,4802 SHEBOYGAN AVE,MADISON,WI,53705
10,"GLENDA, REILLY",BANISTER,4050 VALLEY PIKE,WINCHESTER,VA,22602
11,IMANI,WILSON,1234 YOUR STREET,ATLANTS,GA,30309
12,BRITTNEY RENA,SORRELL,5743 BELCREST ST,HOUSTON,TX,77033
13,ANDREW JASON,SAMPLE,123 MAIN STREET APT. 1,HARRISBURG,PA,17101-0000
14,"MICHELLE, MARIE",MOTORIST,2345 ANYWHERE STREET,ALBANY,NY,12222

***Loc and Iloc***

In [41]:
#Function to get elements of the DataFrame by index
new_df.loc[5]

First Name               MARIE NAKITA
Last Name                    ANDERSON
Address (Street)    8254 PIMPU LN 645
City                       SAN MARCOS
State                              TX
Zip Code                        78666
Name: 5, dtype: str

In [42]:
#Function to get the element by position
new_df.iloc[4]

First Name                    RENEE A
Last Name                       ANDRE
Address (Street)    3300 ACORN STREET
City                           AUSTIN
State                              TX
Zip Code                   12345-0000
Name: 4, dtype: str

In [43]:
#indexing numbers can also change in the Dataframe 

car_name = pd.Series(["BMW", "Mercedes", "Opel", "Mazda", "Toyota", "Honda", "Ford", "Fiat", "Renault", "Peugeot"], index=[1,3,5,7,9,11,13,15,17,19])
car_name

1          BMW
3     Mercedes
5         Opel
7        Mazda
9       Toyota
11       Honda
13        Ford
15        Fiat
17     Renault
19     Peugeot
dtype: str

In [46]:
car_name.loc[3]  # Accessing the first element of the Series

'Mercedes'

In [ ]:
car_name.iloc[3]

'Mazda'

In [51]:
#printing the 3 element of the Series using loc
car_name.loc[:3]

1         BMW
3    Mercedes
dtype: str

In [52]:
#printing the 3 element of the Series using iloc
car_name.iloc[:3]

1         BMW
3    Mercedes
5        Opel
dtype: str